image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent
  tag: "latest" # Última versión estable

main:
  service:
    type: NodePort
    port: 5678
config:
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "host.docker.internal"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_USER: "n8n"
  GENERIC_HOST: "localhost:5678"
  N8N_HOST: "localhost:5678"
  N8N_PROTOCOL: "http"
  REDIS_HOST: "host.docker.internal"
  REDIS_PORT: 6379
secret:
  DB_POSTGRESDB_PASSWORD: "441377" # ¡Cámbialo!
  REDIS_PASSWORD: "441377" # ¡Cámbialo!
persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClass: "microk8s-hostpath"

autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 20